import numpy as np
import itertools
from typing import List, Tuple, Dict, Any

class PrimitivBenchGame:
    """
    Chromatic Cipher - A game of spatial deduction and rule-breaking.

    The game is played on a 5x5 grid. The player is shown an 'observed_grid' of colors (0-4)
    and is told that one row is a 'wildcard_row'.

    The core mechanics are:
    1.  There is a hidden 'true_grid'. The 'observed_grid' is generated by applying a secret
        XOR mask to each row of the 'true_grid'. (observed_grid[r] = true_grid[r] ^ mask[r]).
    2.  The 'true_grid' is based on a 5x5 Latin Square (each row and column contains all colors 0-4 exactly once).
    3.  However, there is an exception: in the designated 'wildcard_row', the colors that *would*
        perfectly complete the Latin Square have been altered. Specifically, the colors in two
        columns of that row have been swapped.
    
    The player's goal is to deduce which two columns in the wildcard_row were swapped.
    Winning requires sequentially applying a chain of reasoning primitives.
    """

    def __init__(self):
        self.grid_size = 5
        self.num_colors = 5
        self._rng = np.random.default_rng()
        self.reset()

    def reset(self, seed: int = None) -> Dict[str, Any]:
        """
        Resets the game to a new initial state.

        Args:
            seed: A seed for the random number generator to ensure reproducibility.

        Returns:
            A dictionary representing the initial state observable by the player.
            - 'observed_grid': A 5x5 numpy array of observed colors.
            - 'wildcard_row': The index of the row with the special swap rule.
        """
        if seed is not None:
            self._rng = np.random.default_rng(seed)

        # 1. Generate a base Latin Square
        latent_latin_square = self._generate_latin_square()

        # 2. Designate wildcard row and columns to be swapped
        self._wildcard_row_idx = self._rng.integers(0, self.grid_size)
        swapped_cols = self._rng.choice(self.grid_size, 2, replace=False)
        self._solution = tuple(sorted(swapped_cols))

        # 3. Create the 'true_grid' with the swap exception
        self._true_grid = np.copy(latent_latin_square)
        c1, c2 = self._solution
        val1 = self._true_grid[self._wildcard_row_idx, c1]
        val2 = self._true_grid[self._wildcard_row_idx, c2]
        self._true_grid[self._wildcard_row_idx, c1] = val2
        self._true_grid[self._wildcard_row_idx, c2] = val1

        # 4. Generate row masks and the observed grid
        self._row_masks = self._rng.integers(0, self.num_colors, size=self.grid_size)
        self.observed_grid = np.zeros_like(self._true_grid)
        for r in range(self.grid_size):
            self.observed_grid[r, :] = self._true_grid[r, :] ^ self._row_masks[r]

        # 5. Set up game state
        self._done = False
        self._reward = 0.0
        self._win = False

        return self._get_obs()

    def _generate_latin_square(self) -> np.ndarray:
        """Generates a shuffled 5x5 Latin Square."""
        size = self.grid_size
        # Start with a base Latin square (from modular arithmetic)
        ls = np.array([[(i + j) % size for i in range(size)] for j in range(size)], dtype=int)
        
        # Permute rows and columns to randomize it
        row_perm = self._rng.permutation(size)
        ls = ls[row_perm]
        col_perm = self._rng.permutation(size)
        ls = ls[:, col_perm]
        return ls

    def _get_obs(self) -> Dict[str, Any]:
        """Returns the player-facing observation."""
        return {
            'observed_grid': self.observed_grid,
            'wildcard_row': self._wildcard_row_idx
        }

    def step(self, action: Tuple[int, int]) -> Tuple[Dict[str, Any], float, bool, Dict[str, str]]:
        """
        Executes one time-step within the environment.

        Args:
            action: A tuple of two distinct integers (c1, c2) representing the player's guess
                    for the two swapped columns.

        Returns:
            A tuple containing:
            - observation (dict): The current state.
            - reward (float): The reward for the action (1.0 for win, -1.0 for loss).
            - done (bool): Whether the episode has ended.
            - info (dict): Auxiliary diagnostic information.
        """
        if self._done:
            return self._get_obs(), self._reward, self._done, {}

        self._done = True
        
        try:
            # Normalize action for comparison
            if not isinstance(action, (list, tuple)) or len(action) != 2:
                raise ValueError("Action must be a a tuple of two integers.")
            if not (0 <= action[0] < self.grid_size and 0 <= action[1] < self.grid_size and action[0] != action[1]):
                 raise ValueError("Action values must be valid and distinct column indices.")
            
            submitted_solution = tuple(sorted(action))
        except (TypeError, ValueError) as e:
            # Invalid action format results in a loss
            self._reward = -1.0
            self._win = False
            return self._get_obs(), self._reward, self._done, {'error': str(e)}

        if submitted_solution == self._solution:
            self._reward = 1.0
            self._win = True
        else:
            self._reward = -1.0
            self._win = False

        return self._get_obs(), self._reward, self._done, {}

    def render(self, mode: str = "text") -> str:
        """
        Renders a human-readable representation of the game state.

        Args:
            mode: The mode to render with ('text' is supported).

        Returns:
            A string representation of the observed grid and wildcard row.
        """
        if mode != "text":
            raise NotImplementedError("Only 'text' render mode is supported.")
        
        output = "Chromatic Cipher\n"
        output += "----------------\n"
        output += f"Wildcard Row: {self._wildcard_row_idx}\n"
        output += "Observed Grid:\n"
        for r in range(self.grid_size):
            row_str = " ".join(map(str, self.observed_grid[r]))
            if r == self._wildcard_row_idx:
                row_str += "  <-- WILDCARD"
            output += row_str + "\n"
        output += "----------------\n"
        if self._done:
            output += f"Game Over. You submitted {self._last_action if hasattr(self, '_last_action') else 'N/A'}.\n"
            output += f"Result: {'WIN' if self._win else 'LOSS'}\n"
            output += f"Correct solution was: {self._solution}\n"
        return output

    def valid_actions(self) -> List[Tuple[int, int]]:
        """
        Returns a list of all possible valid actions.

        Returns:
            A list of tuples, where each tuple contains two distinct column indices.
        """
        return list(itertools.combinations(range(self.grid_size), 2))

    def is_won(self) -> bool:
        """Returns True if the game has been won, False otherwise."""
        return self._win

if __name__ == '__main__':
    # Example of how to play the game and solve it manually.
    # This demonstrates the required reasoning process.
    
    game = PrimitivBenchGame()
    obs = game.reset(seed=42)
    print("--- Initial State ---")
    print(game.render())

    # --- Optimal Agent Reasoning ---
    
    # B1 (Perception Transform) + A4 (Geometry): Deduce masks and partial true grid
    print("\n--- Agent Reasoning ---")
    all_colors = set(range(game.num_colors))
    deduced_masks = {}
    partial_true_grid = np.full((game.grid_size, game.grid_size), -1)

    print("1. Deducing masks for non-wildcard rows...")
    for r in range(game.grid_size):
        if r != obs['wildcard_row']:
            observed_row = obs['observed_grid'][r]
            for mask_candidate in range(game.num_colors):
                true_row_candidate = observed_row ^ mask_candidate
                if set(true_row_candidate) == all_colors:
                    deduced_masks[r] = mask_candidate
                    partial_true_grid[r] = true_row_candidate
                    print(f"   Row {r}: Mask is {mask_candidate}. True colors: {true_row_candidate}")
                    break
    
    # A4 (Geometry): Infer the 'expected' wildcard row from column constraints
    print("\n2. Deducing 'expected' wildcard row from column constraints...")
    expected_wildcard_row = []
    for c in range(game.grid_size):
        colors_in_col = set(partial_true_grid[:, c])
        colors_in_col.remove(-1) # Remove the placeholder
        missing_color = list(all_colors - colors_in_col)[0]
        expected_wildcard_row.append(missing_color)
    print(f"   Wildcard row {obs['wildcard_row']} should be {expected_wildcard_row} to form a Latin Square.")

    # B2 (Meta-Reasoning): Find the actual wildcard row and compare with expected
    print("\n3. Deducing actual wildcard row and finding the exception...")
    wildcard_observed_row = obs['observed_grid'][obs['wildcard_row']]
    actual_wildcard_row = None
    for mask_candidate in range(game.num_colors):
        true_row_candidate = wildcard_observed_row ^ mask_candidate
        if set(true_row_candidate) == all_colors:
            deduced_masks[obs['wildcard_row']] = mask_candidate
            actual_wildcard_row = list(true_row_candidate)
            print(f"   Wildcard row {obs['wildcard_row']}: Mask is {mask_candidate}. True colors: {actual_wildcard_row}")
            break

    # Find the discrepancy which is the solution
    print("\n4. Comparing expected vs actual to find the swapped columns...")
    mismatched_cols = []
    for c in range(game.grid_size):
        if expected_wildcard_row[c] != actual_wildcard_row[c]:
            mismatched_cols.append(c)
    
    print(f"   Expected: {expected_wildcard_row}")
    print(f"   Actual:   {actual_wildcard_row}")
    print(f"   Discrepancy found in columns: {mismatched_cols}")
    
    # --- Action ---
    action = tuple(mismatched_cols)
    print(f"\n--- Submitting Action: {action} ---")
    
    obs, reward, done, info = game.step(action)
    
    print(f"\n--- Result ---")
    print(f"Reward: {reward}")
    print(f"Done: {done}")
    print(f"Won: {game.is_won()}")
    print("\nFinal state and solution:")
    print(game.render())